FROM n8nio/n8n:1.108.2

# Instala o node da comunidade dentro da pasta de nodes
RUN npm install --prefix /home/node/.n8n/nodes n8n-nodes-efibank n8n-nodes-cnpj n8n-nodes-hotmart n8n-nodes-asaas-v2 \
    @deviobr/n8n-nodes-rdstation @fclebinho/n8n-nodes-negocie@0.0.10

